/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Entite.CTypeFrais;
import Metier.CMetierFicheFrais;
import Tables.CTableFicheFrais;
import Tables.CTableFrais;
import Tables.CTableSecteur;
import Tables.CTableTypeFrais;
import bdd.CBDD;
import bdd.CParametresStockageBDD;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author admin
 */
public class JFrameAjoutTypeFrais extends javax.swing.JFrame {
        // declaration des attributs
   
    protected CMetierFicheFrais metierFicheFrais;
     protected JFrameDeclarerFicheFrais jFrameDeclarerFicheFrais;

    public JFrameDeclarerFicheFrais getjFrameDeclarerFicheFrais() {
        return jFrameDeclarerFicheFrais;
    }

    public void setjFrameDeclarerFicheFrais(JFrameDeclarerFicheFrais jFrameDeclarerFicheFrais) {
        this.jFrameDeclarerFicheFrais = jFrameDeclarerFicheFrais;
    }
   


    public CMetierFicheFrais getMetierFicheFrais() {
        return metierFicheFrais;
    }

    public void setMetierFicheFrais(CMetierFicheFrais metierFicheFrais) {
        this.metierFicheFrais = metierFicheFrais;
    }
    
    /**
     * Creates new form JFrameAjoutTypeFrais
     */
    public JFrameAjoutTypeFrais(CMetierFicheFrais metierFicheFrais) {
        this.setMetierFicheFrais(metierFicheFrais);
        
        initComponents();
        
        String[] ListFrais = this.metierFicheFrais.listeNomFrais();
        
        jComboBoxTypeFrais.setModel(new javax.swing.DefaultComboBoxModel(ListFrais));
      
    }
    
    // pour dessiner une ligne sur l'interface graphique
     public void paint(Graphics g) {
        super.paint(g);  // fixes the immediate problem.
        Graphics2D g2 = (Graphics2D) g;
        Line2D lin = new Line2D.Float(80, 100, 750, 100);
        g2.draw(lin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomVisiteur = new javax.swing.JLabel();
        jTextFieldNomVisiteur = new javax.swing.JTextField();
        jTextFieldMatricule = new javax.swing.JTextField();
        jLabelMatricule = new javax.swing.JLabel();
        jLabeltitre = new javax.swing.JLabel();
        jTextFieldMois = new javax.swing.JTextField();
        jLabelMois = new javax.swing.JLabel();
        jLabelMois1 = new javax.swing.JLabel();
        jTextFieldMois2 = new javax.swing.JTextField();
        jLabelMois2 = new javax.swing.JLabel();
        jTextFieldMois3 = new javax.swing.JTextField();
        jLabelMois3 = new javax.swing.JLabel();
        jButtonEnregistrer = new javax.swing.JButton();
        jComboBoxTypeFrais = new javax.swing.JComboBox<>();
        jButtonRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNomVisiteur.setText("Nom du visiteur:");

        jTextFieldNomVisiteur.setEditable(false);
        jTextFieldNomVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomVisiteurActionPerformed(evt);
            }
        });

        jTextFieldMatricule.setEditable(false);

        jLabelMatricule.setText("Matricule:");

        jLabeltitre.setText("Ajout d’un type de frais forfaitisé ");

        jTextFieldMois.setEditable(false);
        jTextFieldMois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoisActionPerformed(evt);
            }
        });

        jLabelMois.setText("Mois : ");

        jLabelMois1.setText("Type de frais forfaitisé  : ");

        jTextFieldMois2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMois2ActionPerformed(evt);
            }
        });

        jLabelMois2.setText("Quantité : ");

        jTextFieldMois3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMois3ActionPerformed(evt);
            }
        });

        jLabelMois3.setText("Montant : ");

        jButtonEnregistrer.setText("Enregistrer");

        jComboBoxTypeFrais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTypeFrais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeFraisActionPerformed(evt);
            }
        });

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMois, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMois, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabeltitre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRetour)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMois3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMois3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMois2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMois2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMois1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTypeFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonEnregistrer)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatricule)
                    .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltitre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRetour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMois, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMois1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTypeFrais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMois2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMois2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMois3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMois3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnregistrer))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomVisiteurActionPerformed

    }//GEN-LAST:event_jTextFieldNomVisiteurActionPerformed

    private void jTextFieldMoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMoisActionPerformed

    private void jTextFieldMois2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMois2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMois2ActionPerformed

    private void jTextFieldMois3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMois3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMois3ActionPerformed

    private void jComboBoxTypeFraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeFraisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeFraisActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        this.setVisible(false);
        jFrameDeclarerFicheFrais.setVisible(true);
    }//GEN-LAST:event_jButtonRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAjoutTypeFrais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAjoutTypeFrais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAjoutTypeFrais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAjoutTypeFrais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   // instanciation des objets
                CBDD bdd = new CBDD(new CParametresStockageBDD("parametresBdd.properties"));
                CTableTypeFrais tableTypeFrais = new CTableTypeFrais(bdd);
                CTableFrais tableFrais = new CTableFrais(bdd);
                CTableFicheFrais tableFicheFrais = new CTableFicheFrais(bdd, tableFrais);
                CMetierFicheFrais metierFicheFrais = new CMetierFicheFrais(tableFicheFrais, tableTypeFrais, tableFrais);
                
                JFrameAjoutTypeFrais jFrameAjoutTypeFrais = new JFrameAjoutTypeFrais(metierFicheFrais);
                jFrameAjoutTypeFrais.setVisible(true);
            }
        });
    }

    public JButton getjButtonEnregistrer() {
        return jButtonEnregistrer;
    }

    public void setjButtonEnregistrer(JButton jButtonEnregistrer) {
        this.jButtonEnregistrer = jButtonEnregistrer;
    }

    public JComboBox<String> getjComboBoxTypeFrais() {
        return jComboBoxTypeFrais;
    }

    public void setjComboBoxTypeFrais(JComboBox<String> jComboBoxTypeFrais) {
        this.jComboBoxTypeFrais = jComboBoxTypeFrais;
    }

    public JLabel getjLabelMatricule() {
        return jLabelMatricule;
    }

    public void setjLabelMatricule(JLabel jLabelMatricule) {
        this.jLabelMatricule = jLabelMatricule;
    }

    public JLabel getjLabelMois() {
        return jLabelMois;
    }

    public void setjLabelMois(JLabel jLabelMois) {
        this.jLabelMois = jLabelMois;
    }

    public JLabel getjLabelMois1() {
        return jLabelMois1;
    }

    public void setjLabelMois1(JLabel jLabelMois1) {
        this.jLabelMois1 = jLabelMois1;
    }

    public JLabel getjLabelMois2() {
        return jLabelMois2;
    }

    public void setjLabelMois2(JLabel jLabelMois2) {
        this.jLabelMois2 = jLabelMois2;
    }

    public JLabel getjLabelMois3() {
        return jLabelMois3;
    }

    public void setjLabelMois3(JLabel jLabelMois3) {
        this.jLabelMois3 = jLabelMois3;
    }

    public JLabel getjLabelNomVisiteur() {
        return jLabelNomVisiteur;
    }

    public void setjLabelNomVisiteur(JLabel jLabelNomVisiteur) {
        this.jLabelNomVisiteur = jLabelNomVisiteur;
    }

    public JLabel getjLabeltitre() {
        return jLabeltitre;
    }

    public void setjLabeltitre(JLabel jLabeltitre) {
        this.jLabeltitre = jLabeltitre;
    }

    public JTextField getjTextFieldMatricule() {
        return jTextFieldMatricule;
    }

    public void setjTextFieldMatricule(JTextField jTextFieldMatricule) {
        this.jTextFieldMatricule = jTextFieldMatricule;
    }

    public JTextField getjTextFieldMois() {
        return jTextFieldMois;
    }

    public void setjTextFieldMois(JTextField jTextFieldMois) {
        this.jTextFieldMois = jTextFieldMois;
    }

    public JTextField getjTextFieldMois2() {
        return jTextFieldMois2;
    }

    public void setjTextFieldMois2(JTextField jTextFieldMois2) {
        this.jTextFieldMois2 = jTextFieldMois2;
    }

    public JTextField getjTextFieldMois3() {
        return jTextFieldMois3;
    }

    public void setjTextFieldMois3(JTextField jTextFieldMois3) {
        this.jTextFieldMois3 = jTextFieldMois3;
    }

    public JTextField getjTextFieldNomVisiteur() {
        return jTextFieldNomVisiteur;
    }

    public void setjTextFieldNomVisiteur(JTextField jTextFieldNomVisiteur) {
        this.jTextFieldNomVisiteur = jTextFieldNomVisiteur;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JComboBox<String> jComboBoxTypeFrais;
    private javax.swing.JLabel jLabelMatricule;
    private javax.swing.JLabel jLabelMois;
    private javax.swing.JLabel jLabelMois1;
    private javax.swing.JLabel jLabelMois2;
    private javax.swing.JLabel jLabelMois3;
    private javax.swing.JLabel jLabelNomVisiteur;
    private javax.swing.JLabel jLabeltitre;
    private javax.swing.JTextField jTextFieldMatricule;
    private javax.swing.JTextField jTextFieldMois;
    private javax.swing.JTextField jTextFieldMois2;
    private javax.swing.JTextField jTextFieldMois3;
    private javax.swing.JTextField jTextFieldNomVisiteur;
    // End of variables declaration//GEN-END:variables
}
