/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Metier.CMetierFicheFrais;
import Tables.CTableFicheFrais;
import Tables.CTableFrais;
import Tables.CTableSecteur;
import Tables.CTableTypeFrais;
import bdd.CBDD;
import bdd.CParametresStockageBDD;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author admin
 */
public class JFrameConnexion extends javax.swing.JFrame {
    // declaration des attributs
    protected CBDD bdd;
    protected CTableSecteur tableSecteur;
    protected CTableTypeFrais tableTypeFrais;
    protected CTableFrais tableFrais;
    protected CTableFicheFrais tableFicheFrais;
    protected CMetierFicheFrais  metierFicheFrais;
    protected JFrameAccueil jFrameAccueil;
   // protected JFrameDeclarerFicheFrais jFrameDeclarerFicheFrais;

    public JFrameAccueil getjFrameAccueil() {
        return jFrameAccueil;
    }

    public void setjFrameAccueil(JFrameAccueil jFrameAccueil) {
        this.jFrameAccueil = jFrameAccueil;
    }

    public CMetierFicheFrais getMetierFicheFrais() {
        return metierFicheFrais;
    }

    public void setMetierFicheFrais(CMetierFicheFrais metierFicheFrais) {
        this.metierFicheFrais = metierFicheFrais;
    }
    
    
    
    /**
     * Creates new form JFrameConnexion
     */
    public JFrameConnexion(JFrameAccueil jFrameAccueil, CMetierFicheFrais metierFicheFrais) {
        this.setjFrameAccueil(jFrameAccueil);
        this.setMetierFicheFrais(metierFicheFrais);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNom = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelMdp = new javax.swing.JLabel();
        jButtonSeConnecter = new javax.swing.JButton();
        jPasswordFieldMdp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNom.setText("Nom : ");

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jLabelMdp.setText("Mot de passe : ");

        jButtonSeConnecter.setText("Se connecter");
        jButtonSeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeConnecterActionPerformed(evt);
            }
        });

        jPasswordFieldMdp.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSeConnecter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPasswordFieldMdp))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButtonSeConnecter)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jButtonSeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeConnecterActionPerformed
       // on ouvre la fenetre JFrameAccueil
      //JFrameConnexion jFrameConnexion = new JFrameConnexion(); 
      //this.metierFicheFrais = new CMetierFicheFrais(jFrameConnexion.tableFicheFrais, jFrameConnexion.tableTypeFrais);
      this.metierFicheFrais.setNomVisiteur(this.getjTextFieldNom().getText());
      this.metierFicheFrais.setMatricule(this.getjPasswordFieldMdp().getText());
      this.jFrameAccueil.getjTextFieldMatricule().setText(this.metierFicheFrais.getMatricule());
      this.jFrameAccueil.getjTextFieldNomVisiteur().setText(this.metierFicheFrais.getNomVisiteur());
   
      this.jFrameAccueil.setVisible(true);
    }//GEN-LAST:event_jButtonSeConnecterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CBDD bdd = new CBDD(new CParametresStockageBDD("parametresBdd.properties"));
                CTableTypeFrais tableTypeFrais = new CTableTypeFrais(bdd);
                CTableFrais tableFrais = new CTableFrais(bdd);
                CTableFicheFrais tableFicheFrais = new CTableFicheFrais(bdd, tableFrais);
                CMetierFicheFrais metierFicheFrais = new CMetierFicheFrais(tableFicheFrais, tableTypeFrais, tableFrais);
                JFrameAjoutTypeFrais jFrameAjoutTypeFrais = new JFrameAjoutTypeFrais(metierFicheFrais);
                 JFrameDeclarerFicheFrais jFrameDeclarerFicheFrais = new JFrameDeclarerFicheFrais(metierFicheFrais, jFrameAjoutTypeFrais );
                JFrameAccueil jFrameAccueil = new JFrameAccueil(jFrameDeclarerFicheFrais, metierFicheFrais);
               JFrameConnexion jFrameConnexion = new JFrameConnexion(jFrameAccueil, metierFicheFrais); 
             
               
               jFrameConnexion.setVisible(true);
            }
        });
    }

    public JButton getjButtonSeConnecter() {
        return jButtonSeConnecter;
    }

    public void setjButtonSeConnecter(JButton jButtonSeConnecter) {
        this.jButtonSeConnecter = jButtonSeConnecter;
    }

    public JPasswordField getjPasswordFieldMdp() {
        return jPasswordFieldMdp;
    }

    public void setjPasswordFieldMdp(JPasswordField jPasswordFieldMdp) {
        this.jPasswordFieldMdp = jPasswordFieldMdp;
    }

    public JTextField getjTextFieldNom() {
        return jTextFieldNom;
    }

    public void setjTextFieldNom(JTextField jTextFieldNom) {
        this.jTextFieldNom = jTextFieldNom;
    }

  

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSeConnecter;
    private javax.swing.JLabel jLabelMdp;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JPasswordField jPasswordFieldMdp;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables

    
}
