/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Entite.CFicheFrais;
import Entite.CFrais;
import Metier.CMetierFicheFrais;
import Tables.CTableFicheFrais;
import Tables.CTableFrais;
import Tables.CTableRegion;
import Tables.CTableSecteur;
import Tables.CTableTravail;
import Tables.CTableTypeFrais;
import Tables.CTableVisiteur;
import bdd.CBDD;
import bdd.CParametresStockageBDD;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class JFrameAccueil extends JFrame {

    // declaration des attributs
    protected CBDD bdd;
    protected CTableSecteur tableSecteur;
    protected CTableTypeFrais tableTypeFrais;
    protected CTableFrais tableFrais;
    protected CTableFicheFrais tableFicheFrais;
    protected CMetierFicheFrais metierFicheFrais;
    protected JFrameDeclarerFicheFrais jFrameDeclarerFicheFrais;
    protected JFrameAjoutTypeFrais jFrameAjoutTypeFrais;
    protected JFrameConnexion jFrameConnexion;

    public JFrameConnexion getjFrameConnexion() {
        return jFrameConnexion;
    }

    public void setjFrameConnexion(JFrameConnexion jFrameConnexion) {
        this.jFrameConnexion = jFrameConnexion;
    }
    
    
    public void setjFrameDeclarerFicheFrais(JFrameDeclarerFicheFrais jFrameDeclarerFicheFrais) {
        this.jFrameDeclarerFicheFrais = jFrameDeclarerFicheFrais;
    }
    

    public CMetierFicheFrais getMetierFicheFrais() {
        return metierFicheFrais;
    }

    public void setMetierFicheFrais(CMetierFicheFrais metierFicheFrais) {
        this.metierFicheFrais = metierFicheFrais;
    }

    /**
     * Creates new form JFrameAccueil
     */
    public JFrameAccueil(JFrameDeclarerFicheFrais jFrameDeclarerFicheFrais, CMetierFicheFrais metierFicheFrais) {
        this.setjFrameDeclarerFicheFrais(jFrameDeclarerFicheFrais);
        this.setMetierFicheFrais(metierFicheFrais);

        initComponents();
       
        // insertion des valeurs (mois)dans la comboBox
        // String[] tab = {"Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Décembre"};
        //  jComboBoxMois.setModel(new javax.swing.DefaultComboBoxModel(tab));

        // on récupère la liste des mois (où on a une fiche frais) correspondant au matricule choisis
        //String[] tableauMois = metierFicheFrais.listeMois(this.jTextFieldMatricule.getText());
        String[] tableauMois = this.metierFicheFrais.listeMois("1234");
        jComboBoxMois.setModel(new javax.swing.DefaultComboBoxModel(tableauMois));

        // on modifie le titre de la fenetre
        this.setTitle("Accueil - Rechercher une fiche de frais");

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //quitte frame lors fermeture

    }

    // pour dessiner une ligne sur l'interface graphique
    public void paint(Graphics g) {
        super.paint(g);  // fixes the immediate problem.
        Graphics2D g2 = (Graphics2D) g;
        Line2D lin = new Line2D.Float(80, 100, 750, 100);
        g2.draw(lin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomVisiteur = new javax.swing.JLabel();
        jTextFieldNomVisiteur = new javax.swing.JTextField();
        jLabelMatricule = new javax.swing.JLabel();
        jTextFieldMatricule = new javax.swing.JTextField();
        jLabelTitreConsulterFicheFrais = new javax.swing.JLabel();
        jLabelSelectMois = new javax.swing.JLabel();
        jComboBoxMois = new javax.swing.JComboBox<>();
        jButtonValider = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonNouvelleFiche = new javax.swing.JButton();
        jLabelEtatFicheFrais = new javax.swing.JLabel();
        jTextFieldEtatFicheFrais = new javax.swing.JTextField();
        jLabelDateDerniereModif = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldDateDerniereModif = new javax.swing.JTextField();
        jLabelDate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHorsClassif = new javax.swing.JTable();
        jButtonDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNomVisiteur.setText("Nom du visiteur:");

        jTextFieldNomVisiteur.setEditable(false);
        jTextFieldNomVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomVisiteurActionPerformed(evt);
            }
        });

        jLabelMatricule.setText("Matricule:");

        jTextFieldMatricule.setEditable(false);

        jLabelTitreConsulterFicheFrais.setText("Consulter mes fiches de frais");

        jLabelSelectMois.setText("Selectionner un mois :");

        jComboBoxMois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMoisActionPerformed(evt);
            }
        });

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jButtonNouvelleFiche.setText("Nouvelle Fiche");
        jButtonNouvelleFiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouvelleFicheActionPerformed(evt);
            }
        });

        jLabelEtatFicheFrais.setText("Etat de la fiche de frais : ");

        jTextFieldEtatFicheFrais.setEditable(false);
        jTextFieldEtatFicheFrais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEtatFicheFraisActionPerformed(evt);
            }
        });

        jLabelDateDerniereModif.setText("Date de dernière modification : ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type de frais forfaitisé", "Quantité", "Montant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextFieldDateDerniereModif.setEditable(false);

        jTableHorsClassif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Hors Classification", "Montant Hors Classification"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableHorsClassif);

        jButtonDeconnexion.setText("Deconnexion");
        jButtonDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEtatFicheFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEtatFicheFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSelectMois, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jTextFieldNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jButtonValider)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jLabelTitreConsulterFicheFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonModifier)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonSupprimer)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonNouvelleFiche))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDateDerniereModif, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabelMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldDateDerniereModif, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(296, 296, 296))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonDeconnexion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeconnexion)
                        .addGap(17, 17, 17)
                        .addComponent(jLabelTitreConsulterFicheFrais)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSelectMois)
                            .addComponent(jComboBoxMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonValider))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEtatFicheFrais)
                            .addComponent(jTextFieldEtatFicheFrais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMatricule)
                            .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModifier)
                            .addComponent(jButtonSupprimer)
                            .addComponent(jButtonNouvelleFiche))
                        .addGap(12, 12, 12)
                        .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDateDerniereModif)
                            .addComponent(jTextFieldDateDerniereModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomVisiteurActionPerformed

    }//GEN-LAST:event_jTextFieldNomVisiteurActionPerformed

    private void jComboBoxMoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMoisActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:
        // this.jTextFieldNomVisiteur.setText("Nom du visiteur:");
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // metier.valider(this.jTextFieldMatricule.getText(),this.jComboBoxMois.getSelectedItem(),this.jTable1);              

        // on récupère la fiche frais de type CFicheFrais correspondant au matricule et mois choisis
        ArrayList<CFicheFrais> list = metierFicheFrais.valider(this.jTextFieldMatricule.getText(), this.jComboBoxMois.getSelectedIndex()+1);

        //pour afficher l'etape de la fiche de frais dans le champ EtatFicheFrais
        jTextFieldEtatFicheFrais.setText(list.get(0).getEtape());

        // Pour afficher la date, on transforme le format date gregorian calendar au format dd/MM/yyyy
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldDateDerniereModif.setText(dateFormat.format(list.get(0).getDateDerniereModif().getTime()));

        // On ajoute les Type de frais , quantité et montant forfaitisé dans la jTable1, de la liste de frais correspondant à cette fiche de frais
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // on supprime les lignes existentes de la jTable1 sauf l'entête
        list.get(0).getListeFrais().forEach((frais) -> {
            model.addRow(new Object[]{
                frais.getTypeFrais().getLabel(), frais.getQuantite(), frais.getMontant()});
        });

        // On ajoute le Nombre Hors classification et le montant Hors classification dans la jTableHorsClassif, de la fiche de frais
        DefaultTableModel model2 = (DefaultTableModel) jTableHorsClassif.getModel();
        model2.setRowCount(0); // on supprime les lignes existentes de la jTableHorsClassif sauf l'entête
        // on insere la ligne dans jTableHorsClassif
        model2.addRow(new Object[]{
            list.get(0).getNbHorsClassif(), list.get(0).getMontantHorsClassif()});


    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jTextFieldEtatFicheFraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEtatFicheFraisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEtatFicheFraisActionPerformed

    private void jButtonNouvelleFicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouvelleFicheActionPerformed
         this.jFrameDeclarerFicheFrais.getjTextFieldMatricule().setText(this.metierFicheFrais.getMatricule());
      this.jFrameDeclarerFicheFrais.getjTextFieldNomVisiteur().setText(this.metierFicheFrais.getNomVisiteur());
   
      this.jFrameDeclarerFicheFrais.setVisible(true);
        
    }//GEN-LAST:event_jButtonNouvelleFicheActionPerformed

    private void jButtonDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeconnexionActionPerformed
        this.setVisible(false);
        this.metierFicheFrais.setNomVisiteur("");
      this.metierFicheFrais.setMatricule("");
      this.jFrameConnexion.getjTextFieldNom().setText(this.metierFicheFrais.getMatricule());
      this.jFrameConnexion.getjPasswordFieldMdp().setText(this.metierFicheFrais.getNomVisiteur());
      
        jFrameConnexion.setVisible(true);
    }//GEN-LAST:event_jButtonDeconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // instanciation des objets
                CBDD bdd = new CBDD(new CParametresStockageBDD("parametresBdd.properties"));
                CTableTypeFrais tableTypeFrais = new CTableTypeFrais(bdd);
                CTableFrais tableFrais = new CTableFrais(bdd);
                CTableFicheFrais tableFicheFrais = new CTableFicheFrais(bdd, tableFrais);
                CMetierFicheFrais metierFicheFrais = new CMetierFicheFrais(tableFicheFrais, tableTypeFrais, tableFrais);
                JFrameAjoutTypeFrais jFrameAjoutTypeFrais = new JFrameAjoutTypeFrais(metierFicheFrais);
                 JFrameDeclarerFicheFrais jFrameDeclarerFicheFrais = new JFrameDeclarerFicheFrais(metierFicheFrais, jFrameAjoutTypeFrais );
                JFrameAccueil jFrameAccueil = new JFrameAccueil(jFrameDeclarerFicheFrais, metierFicheFrais);
                //jFrameAccueil.bdd=new CBDD(new CParametresStockageBDD("parametresBdd.properties"));

                // jFrameAccueil.tableTypeFrais = new CTableTypeFrais(jFrameAccueil.bdd);
                // jFrameAccueil.tableFrais = new CTableFrais(jFrameAccueil.bdd);
                // jFrameAccueil.tableFicheFrais = new CTableFicheFrais(jFrameAccueil.bdd, jFrameAccueil.tableFrais);
                jFrameAccueil.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeconnexion;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonNouvelleFiche;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox<String> jComboBoxMois;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDateDerniereModif;
    private javax.swing.JLabel jLabelEtatFicheFrais;
    private javax.swing.JLabel jLabelMatricule;
    private javax.swing.JLabel jLabelNomVisiteur;
    private javax.swing.JLabel jLabelSelectMois;
    private javax.swing.JLabel jLabelTitreConsulterFicheFrais;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableHorsClassif;
    private javax.swing.JTextField jTextFieldDateDerniereModif;
    private javax.swing.JTextField jTextFieldEtatFicheFrais;
    private javax.swing.JTextField jTextFieldMatricule;
    private javax.swing.JTextField jTextFieldNomVisiteur;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextFieldMatricule() {
        return jTextFieldMatricule;
    }

    public JTextField getjTextFieldNomVisiteur() {
        return jTextFieldNomVisiteur;
    }


}
